# Generated by Django 6.0.2 on 2026-02-11 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_alter_idea_submitted_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='votes',
        ),
        migrations.AddField(
            model_name='idea',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='voted_ideas', to=settings.AUTH_USER_MODEL),
        ),
    ]
