# Generated by Django 6.0.2 on 2026-02-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_remove_idea_votes_idea_voters'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
