# Generated by Django 6.0.2 on 2026-03-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0009_department_description_department_video_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nikita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
