# Generated by Django 6.0.2 on 2026-03-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0010_nikita'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bonus_euros',
            field=models.IntegerField(default=0),
        ),
    ]
