# Generated by Django 6.0.2 on 2026-03-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0011_profile_bonus_euros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='idea',
            name='accepted_by',
            field=models.ManyToManyField(blank=True, related_name='installed_ideas', to='gameplay.department'),
        ),
    ]
