# Generated by Django 6.0.2 on 2026-04-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0014_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='solution_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='solution_image',
            field=models.ImageField(blank=True, null=True, upload_to='solutions/'),
        ),
    ]
