# Generated by Django 6.0.2 on 2026-04-05 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0016_ideacategory_idea_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subdomain', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='actionlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameplay.tenant'),
        ),
        migrations.AddField(
            model_name='department',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameplay.tenant'),
        ),
        migrations.AddField(
            model_name='idea',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameplay.tenant'),
        ),
        migrations.AddField(
            model_name='ideacategory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameplay.tenant'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameplay.tenant'),
        ),
        migrations.AddField(
            model_name='nikita',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameplay.tenant'),
        ),
        migrations.AddField(
            model_name='problem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameplay.tenant'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameplay.tenant'),
        ),
        migrations.AddField(
            model_name='question',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameplay.tenant'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameplay.tenant'),
        ),
        migrations.AddField(
            model_name='training',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameplay.tenant'),
        ),
        migrations.AddField(
            model_name='trainingfeedback',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameplay.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='ideacategory',
            unique_together={('tenant', 'name')},
        ),
    ]
