# Generated by Django 6.0.2 on 2026-04-05 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0018_backfill_tenant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='training',
            unique_together={('tenant', 'title')},
        ),
        migrations.DeleteModel(
            name='Nikita',
        ),
    ]
