# Generated by Django 6.0.2 on 2026-04-05 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0019_alter_training_unique_together_delete_nikita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.tenant'),
        ),
        migrations.AlterField(
            model_name='department',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.tenant'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.tenant'),
        ),
        migrations.AlterField(
            model_name='ideacategory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.tenant'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.tenant'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.tenant'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.tenant'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.tenant'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.tenant'),
        ),
        migrations.AlterField(
            model_name='training',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.tenant'),
        ),
        migrations.AlterField(
            model_name='trainingfeedback',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.tenant'),
        ),
    ]
