# Generated by Django 6.0.2 on 2026-04-06 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0020_alter_actionlog_tenant_alter_department_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gameplay.department'),
        ),
    ]
