# Generated by Django 6.0.2 on 2026-04-06 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0019_backfill_invite_tenant'),
        ('gameplay', '0022_invite'),
    ]

    operations = [
    ]
