# Generated by Django 6.0.2 on 2026-04-15 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0023_merge_0019_backfill_invite_tenant_0022_invite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='tenant_admin',
            field=models.ForeignKey(blank=True, help_text='Assign an admin for this company.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_tenants', to=settings.AUTH_USER_MODEL),
        ),
    ]
