# Generated by Django 6.0.2 on 2026-04-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0024_tenant_tenant_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
