# Generated by Django 6.0.2 on 2026-05-15 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0026_redeemedreward'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_accepted', models.IntegerField(default=100, help_text='Points awarded when an idea is accepted/implemented')),
                ('quiz_completed', models.IntegerField(default=10, help_text='Points per correct answer in a quiz')),
                ('problem_solved', models.IntegerField(default=10, help_text='Points awarded when a problem solution is confirmed')),
                ('training_organized', models.IntegerField(default=50, help_text='Bonus euros for organising a cross-dept training')),
                ('idea_submitted', models.IntegerField(default=5, help_text='Points awarded for submitting a new idea')),
                ('training_registered', models.IntegerField(default=5, help_text='Points awarded for registering to a training')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.tenant')),
            ],
            options={
                'verbose_name_plural': 'Point settings',
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='⭐', help_text='Emoji icon for the badge', max_length=10)),
                ('min_points', models.IntegerField(default=0, help_text='Minimum points required to earn this badge')),
                ('color', models.CharField(default='#f59e0b', help_text='Hex color for badge display', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.tenant')),
            ],
            options={
                'ordering': ['min_points'],
                'unique_together': {('tenant', 'name')},
            },
        ),
    ]
