# Generated by Django 6.0.2 on 2026-05-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0028_giftcardstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
